sequenceDiagram
    participant Crypto as Crypto (EasySave)
    participant CryptoSocketClient as CryptoSocketClient (EasySave)
    
    participant SocketServer as SocketServer (CryptoSoft)
    participant Program as Program (CryptoSoft)
    participant FileManager as FileManager (CryptoSoft)