name: Serve DocFX Docs

on:
  push:
    branches:
      - main      # Only trigger when _site is updated in main
  workflow_dispatch:   # Optional: allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest   # Windows not needed, no build only serve

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Deploy _site to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          force_orphan: true